import type { Metadata } from "next";
import localFont from "next/font/local";
import AuthProvider from "@/stores/SessionContext";
import "./globals.css";
import "./styles.scss";
import CompareProvider from "@/stores/CompareContext";
import defaultTheme from "tailwindcss/defaultTheme";

const _font = localFont({
   src: "./Montserrat-VariableFont.ttf",
   weight: "400 700"
});

export const metadata: Metadata = {
   title: "Tech Wars",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body style={{ fontFamily: _font.style.fontFamily +','+ defaultTheme.fontFamily.sans.join(",") }}>
            <AuthProvider>
               <CompareProvider>
                  {children}
                  <div id="portals"></div>
               </CompareProvider>
            </AuthProvider>
         </body>
      </html>
   );
}
