import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import AuthProvider from "@/stores/SessionContext";
import "./globals.css";
import CompareProvider from "@/stores/CompareContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Tech Wars",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={montserrat.className}>
            <AuthProvider>
               <CompareProvider>
                  {children}
                  <div id="portals"></div>
               </CompareProvider>
            </AuthProvider>
         </body>
      </html>
   );
}
